plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/cache_schema.rb"
    - "db/queue_schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "config/environments/**/*"
    - "config/puma.rb"
    - "config/initializers/devise.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

RSpec/NamedSubject:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "db/migrate/**/*"
  Max: 15
